name: Build and test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update apt
        run: sudo apt-get update

      - name: Install ffmpeg
        run: sudo apt-get install libavcodec-dev libavformat-dev libavutil-dev ffmpeg

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Install python
        run: sudo apt-get install python3

      - name: Test
        run: cd test && python3 test_samples.py
